import pygame
 

pygame.init()
vec = pygame.math.Vector2 #2 for two dimensional

RUNNING = True
START_WITH_SPACE_BAR = False

### RESOLUTION
WINDOW_WIDTH = 1920*0.70
WINDOW_HEIGHT = 1080*0.70

RESIZE_COEFF = WINDOW_WIDTH/1920

window = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))
pygame.display.set_caption("You Shall Not Pass")

### FPS
FPS = 60
CLOCK = pygame.time.Clock() 

### MUSIC
MUSIC_FILE_PATH = "Audio/Music/Age_of_War_Theme_Soundtrack.mp3"
FADE_UP_TIME = 3.0 # in seconds
MUSIC_VOLUME = 0.1

#### BACKGROUND
BACKGROUND_IMAGE_PATH = "Assets/Background/background1.png"
BACKGROUND_SQUARE_SIDE = WINDOW_HEIGHT/8.0

#### MOUSE
MOUSE_IMAGE_PATH = "Assets/Cursor/cursor6.png"
MOUSE_RESIZE_FACTOR = 0.4*RESIZE_COEFF
MOUSE_RATIO_FOR_HITBOX = 1.0

MOUSE_CARRIED_IMAGE_ALPHA = 100

MOUSE_VALID_BOX_IMAGE_PATH = "Assets/Tower/Valid_boxes/valid.png"
MOUSE_VALID_BOX_IMAGE_ALPHA = 150
MOUSE_NOT_VALID_BOX_IMAGE_PATH = "Assets/Tower/Valid_boxes/not_valid.png"
MOUSE_NOT_VALID_BOX_IMAGE_ALPHA = 150

#### MENU
MENU_BUTTON_SIZE = [BACKGROUND_SQUARE_SIDE,BACKGROUND_SQUARE_SIDE]
MENU_ARCANE_TOWER_BUTTON_IMAGE_PATH = "Assets/Tower/ToursMagique/Blanche/Frametest.png"
MENU_BALLISTA_BUTTON_IMAGE_PATH = "Assets/Tower/Baliste/AnimAttack/0001.png"

#### ENNEMIES SPAWNING 
SPAWNING_WITH_SCRIPT = False
SPAWNING_MARGIN_SPACE = 0.1   ## *background.bush_width
SPAWNING_INITIAL_TIME = 4.0 # in seconds

TIME_P1 = 1000000   ## time phase n1 in seconds
P1_GOBELIN_SPAWNING_PERIOD = 2.0   ## in seconds
P1_OGRE_SPAWNING_PERIOD = 4.0   ## in seconds

###############     BASE     ###############
BASE_GATE_HP_MAX = 10000


###############     ENNEMIES     ###############

#### GOBELIN
GOBELIN_HP_MAX = 20.0
GOBELIN_DAMAGE = 2.5
GOBELIN_VELOCITY = 0.2 * RESIZE_COEFF # pixel by ms
GOBELIN_HITBOX_FACTOR = 1.0

GOBELIN_RESIZE_FACTOR = 0.5*RESIZE_COEFF #   pixel
GOBELIN_OFFSET = [50* RESIZE_COEFF,-25* RESIZE_COEFF] 
GOBELIN_CENTER_VECTOR = [0.26, 0.63] 

GOBELIN_WALKING_IMAGE_PATH = "Assets/Ennemies/Gobelin/WalkAnim/"
GOBELIN_NUMBER_FRAME_WALKING = 20
GOBELIN_ANIMATION_WALKING_TOTAL_TIME = 600 # in ms
GOBELIN_STOP_WALKING_FRAME = 11
 
GOBELIN_NUMBER_FRAME_TRANSITION  = 1
GOBELIN_TRANSITION_IMAGE_PATH = "Assets/Ennemies/Gobelin/TransitionAnim/"
GOBELIN_ANIMATION_TRANSITION_TOTAL_TIME = 300 # in ms

GOBELIN_NUMBER_FRAME_ATTACKING  = 10
GOBELIN_ATTACKING_IMAGE_PATH = "Assets/Ennemies/Gobelin/AttackAnim/"
GOBELIN_ANIMATION_ATTACKING_TOTAL_TIME = 300 # in ms
GOBELIN_HITTING_FRAME = 5


#### OGRE
OGRE_HP_MAX = 60.0
OGRE_DAMAGE = 10
OGRE_VELOCITY = 0.1 * RESIZE_COEFF # pixel by ms
OGRE_HITBOX_FACTOR = 1.0

OGRE_RESIZE_FACTOR = 0.75*RESIZE_COEFF
OGRE_OFFSET = [0* RESIZE_COEFF,-80* RESIZE_COEFF] 
OGRE_CENTER_VECTOR = [0.37, 0.59]

OGRE_WALKING_IMAGE_PATH = "Assets/Ennemies/Ogre/WalkAnim/"
OGRE_NUMBER_FRAME_WALKING = 20
OGRE_ANIMATION_WALKING_TOTAL_TIME = 600*1.5 # in ms
OGRE_STOP_WALKING_FRAME = 16
 
OGRE_NUMBER_FRAME_TRANSITION  = 4
OGRE_TRANSITION_IMAGE_PATH = "Assets/Ennemies/Ogre/TransitionAnim/"
OGRE_ANIMATION_TRANSITION_TOTAL_TIME = 300 # in ms

OGRE_NUMBER_FRAME_ATTACKING  = 15
OGRE_ATTACKING_IMAGE_PATH = "Assets/Ennemies/Ogre/AttackAnim/"
OGRE_ANIMATION_ATTACKING_TOTAL_TIME = 300*3 # in ms
OGRE_HITTING_FRAME = 13


###############     TOWERS     ###############
TOWER_RECT_RANGE_IMAGE_PATH = "Assets/Tower/Range_boxes/rect_range.png"
TOWER_RECT_RANGE_IMAGE_ALPHA = 100
TOWER_CIRCLE_RANGE_IMAGE_PATH = "Assets/Tower/Range_boxes/circle_range.png"
TOWER_CIRCLE_RANGE_IMAGE_ALPHA = 100

#### ARCANE_TOWER
ARCANE_TOWER_HP_MAX = 20.0
ARCANE_TOWER_IMAGE_PATH = "Assets/Tower/ToursMagique/Blanche/Frametest2.png"
ARCANE_TOWER_OFFSET = [-0.0*BACKGROUND_SQUARE_SIDE,-0.6*BACKGROUND_SQUARE_SIDE] 
ARCANE_TOWER_RESIZE_FACTOR = 0.15*RESIZE_COEFF
ARCANE_TOWER_CENTER_VECTOR = [0.5, 0.25]
ARCANE_TOWER_FIRING_OFFSET = [0,0]

ARCANE_TOWER_FIRING_PERIOD = 900 # in ms
ARCANE_TOWER_RANGE = 2.5 # multiplied by the square side


#### BALLISTA
BALLISTA_HP_MAX = 20.0
BALLISTA_ATTACK_IMAGE_PATH = "Assets/Tower/Baliste/AnimAttack/"
BALLISTA_OFFSET = [0* RESIZE_COEFF,-10* RESIZE_COEFF] 
BALLISTA_RESIZE_FACTOR = 0.4*RESIZE_COEFF
BALLISTA_CENTER_VECTOR = [0.5, 0.5]
BALLISTA_FIRING_OFFSET = [0* RESIZE_COEFF,2* RESIZE_COEFF] 
BALLISTA_NUMBER_FRAME_ATTACKING = 45
BALLISTA_FIRING_FRAME = 5

BALLISTA_FIRING_PERIOD = 1800 # in ms
BALLISTA_RANGE = 6.0 # multiplied by the square side


###############     PROJECTILES     ###############

#### BOLT
BOLT_IMAGE_PATH = "Assets/Tower/Baliste/CarreauBaliste.png"
BOLT_RESIZE_FACTOR = 0.8*RESIZE_COEFF
# BOLT_CENTOR_VECTOR = [0.58,0.47]
BOLT_RATIO_FOR_IMPACT = 0.75

BOLT_DAMAGE = 5.0
BOLT_VELOCITY = 2.0 * RESIZE_COEFF # pixel by ms